### ISSUE TITLE
Version of bundle for Mac is broken

### ISSUE THREAD

**Issue by bykka** [bykka/dynamoit#20]
@prayforbirdies reposted that mac release bundle does not run on seqouia macos

![image](https://github.com/user-attachments/assets/f6887c96-85c0-4849-a536-e9cc6b5da4ed)

**Comment by mattes3** [comment]
Same here. Is there a solution?

**Comment by bykka** [comment]
Finally, I have a MacBook, so I hope to fix it soon.

**Comment by bykka** [comment]
There is a new release 1.2.1 - the mac version should work now. I tested on my new mac and it works.

**Comment by pabloiarriola** [comment]
its working for me
